ENV PATH="/usr/local/bin:$PATH"

release: apt-get update && apt-get install -y python3-pip && pip install rasa
web: rasa run --enable-api --port 5005
worker: rasa run actions --port 5055

# release: apt-get update && apt-get install -y python3-pip && pip install rasa && source /opt/venv/bin/activate && rasa --version
# web: source /opt/venv/bin/activate && rasa run --enable-api --port 5005
# worker: source /opt/venv/bin/activate && rasa run actions --port 5055

# release: pip install rasa
# web: rasa run --enable-api --port 5005
# worker: rasa run actions --port 5055